### ISSUE TITLE
[FEATURE] work with bare repo

### ISSUE THREAD

**Issue by hqkhan** [arl/gitmux#102]
**Is your feature request related to a problem? Please describe.**
Support for bare repo. Currently, I manage my dotfiles using a bare git repo. A bare git repo requires the `--work-tree` git option to work properly. 

**Describe the solution you'd like**
For a bare git repo, I want the gitmux status bar to work as if nothing is different. I'm not entirely sure on the internals of `gitmux`. If it can read `core.bare=true` git config and act appropriately, it would be nice. Maybe there can be a variable that can be added into the config for a work-tree path? 

I use [t-smart-tmux-session-manager](https://github.com/joshmedeski/t-smart-tmux-session-manager) to create tmux sessions that are rooted at git repos. Similarly, I create it in `GIT_DIR` of my dotfiles repo but I do not get "reading" from gitmux.

**Comment by arl** [comment]
Hi @hqkhan 
Can you explain a bit more about your workflow or use case involving bare repositories?

As I understand, gitmux works well with a clone made from a bare repository.
However, if you cd into the bare repo itself, it's true that gitmux, at the time of writing, doesn't show nothing, as it doesn't consider to be in a work tree. Indeed you can't do a lot while you're in the bare repo, for example all work-tree related commands will fail:

```
aurelien-> git status
fatal: this operation must be run in a work tree

aurelien-> git checkout issue-97
fatal: this operation must be run in a work tree
```

In these conditions, hard to show usable informations. The only thing you can extract from a bare repo would be the HEAD reference, which, as I understand it, is in fact the repository default branch.

**Comment by hqkhan** [comment]
Hi @arl!

> Can you explain a bit more about your workflow or use case involving bare repositories?
I have 2 bare git repos that I used for dotfiles -- 1 public & 1 private. I usually keep a tmux session on a git repo. I was hoping to do the same thing for my bare git repo. The public repo itself lives in `~/.cfg` while the worktree is `$HOME`. 

Is there a way for me to get gitmux to capture repo status information?

**Comment by arl** [comment]
What information would you expect gitmux to show in while in a bare repo?
And if you weren't using gitmux, what git commands would you type to get that information?

**Comment by hqkhan** [comment]
Apologies, I should've specified further.

So, what I'm hoping can happen is the following:

1. `gitmux` tries the default commands that it does via `git ...`
2. If (1) fails, there is a set of alternative `git-dir` + `worktrees` that it can try instead as a fallback
3. If both (1) & (2) failed, then no info is presented

Basically, through gitmux's config, we'd pass in a list of git-dir / worktrees tuple per entry.

Either that or maybe try a different "binary" altogether. The other "binary" or alias can be something like:

```
#!/bin/sh
git -c status.showUntrackedFiles=no --git-dir=${PATH_TO_REPO} --work-tree=${HOME} -C ${HOME} "$@"
```

**Comment by arl** [comment]
I see.
This is a very specific use case and I'm honestly not sure that gitmux is the best job to handle this.
However, you could probably manage that git-dir/work-trees tuples list elsewhere, and with a bit of PROMPT_COMMAND magic (if you use bash, even easier if you use more modern shells), and the fact that the `gitmux` command accepts a directory, I think you could solve your use case.

By default, running `gitmux` is like running `gitmux .` (current directory). But if you explicitly pass another directory, like `gitmux /path/to/my/work-tree` then `gitmux` would show the git status of  that other directory instead.

Hope that helps! :)

**Comment by hqkhan** [comment]
Oh interesting! I hadn't realized that you can pass in another directory. I'll play around with that and see how it works. Thank you!

**Comment by arl** [comment]
You're welcome
