### ISSUE TITLE
[BUG] The clear style doesn't appear to remove bold formatting

### ISSUE THREAD

**Issue by PBHDK** [arl/gitmux#107]
I'm not sure I'm correct here, but since I don't have time to dig any deeper right now, I figured a bug report would still be helpful. Probably a fairly straightforward fix if someone can confirm that this is indeed a bug (maybe there's something wrong on my side). For anyone looking for a workaround, just remove the bold formatting.

**Describe the bug**
When the gitmux style ends with an element with bold formatting specified, the `clear` style won't remove it, and all elements that follow gitmux in the tmux status bar will carry over the bold formatting.

**To Reproduce**
In `gitmux.conf`, set: 
```
clear: '#[fg=default]'
divergence: '#[fg=white, bold]'
layout: [branch, divergence]
```

and in `tmux.conf`, set, for instance:
```
set -g status-right '#(gitmux -cfg <your_config> "#{pane_current_path}") [#S]'
```

Now, the session, which was specified via `[#S]` will appear in bold.

**Environment:**
 - gitmux version: 0.10.3
 - tmux version: 3.3a
 - macOS Sonoma 14.2.1
 - zsh

**Comment by arl** [comment]
@PBHDK 
Thank you for reporting and tracking this down
Fixed on master
tagged release will follow
