### ISSUE TITLE
Changing configuration with option flag

### ISSUE THREAD

**Issue by Chacon-tu-drema** [arl/gitmux#110]
**Is your feature request related to a problem? Please describe.**
Hi, Hope everything is going well. 
I have been using this repository for a while now and I love the way it works. I'm only having the problem that; I would prefer if I want to change only one little thing of the configuration, change it by a flag. Having to create a completely new file when the only thing that I want to do is change the layout is a bit tedious. Let me know what you think of this.

**Describe the solution you'd like**
I would love to be able to give configurations as flags to `gitmux`, something like this:
```
gitmux --layout [branch, "|", flags, "|", stats] "#{pane_current_path}"
or
gitmux --styles-state '#[fg=red]' "#{pane_current_path}"
``` 

**Describe alternatives you've considered**
I haven't consider an alternative, but if this can be solve in a better way let me know

**Comment by arl** [comment]
Hi there

Thank you for the issue.

To be honest and straightforward with you, I'm not sure that configuring gitmux output is best done with flags. Generally one finds the output they want, and rarely changes it. 
What's your use case for changing so often that a configuration file becomes tedious to create? Also why would you need to recreate it, as opposed to just modify the value you want to modify?

**Comment by Chacon-tu-drema** [comment]
Hi :), thank you for such a quick response.

I think you are completely right. Doesn't make sense to put effort into something that only gets changed at the beginning, I didn't think about that. 

The reason why I was asking was that I was adding this to the status in [catppuccin tmux](https://github.com/catppuccin/tmux) and it was more comfortable doing it by option flag. 

Still I think is not worth the effort, especially because as you say is just a one off configuration. 

Thank you and have a nice day :)

**Comment by arl** [comment]
No worries at all. Thanks a lot for your interest in the project.
Have an excellent day!
