### ISSUE TITLE
Tmux Catppiccin integration

### ISSUE THREAD

**Issue by rtalexk** [arl/gitmux#113]
Hi there, I came across this Tmux plugin and I think it is really helpful.

Is there an easy way to integrate it with [Catppuccin for Tmux](https://github.com/catppuccin/tmux/tree/main)? That would be really helpful, that would save me a lot of time doing it myself from scratch.

**Comment by rtalexk** [comment]
I just came across with this PR in Catppuccin, actually it is pretty recent https://github.com/catppuccin/tmux/pull/191, someone else thought the same and addressed it, amazing!

**Comment by arl** [comment]
👍 awesome 😎
