### ISSUE TITLE
Consider possibility to choose/reorder/remove the info shown

### ISSUE THREAD

**Issue by arl** [arl/gitmux#14]
As of now it's not possible to not show the remote  branch, to not show X, to not show Y, to reorder branch and remote, etc, etc. to sum it up, the order and the specific information presented are static.

Not exactly sure how we would make them configurable
Also, is it worth the hassle?

**Comment by casonadams** [comment]
This PR should make this more flexible
https://github.com/arl/gitmux/pull/16

**Comment by arl** [comment]
Hi Cason, nice, thanks for your contribution!

I like how you handled the display order of git components, simple and easy.

I was wondering, could you rename the config option from `Display.Output` to `Display.General` or something similar? Why? Since I imagine, in a second time, we could make the order and presence of the flags (added, deleted, etc.) also configurable, so we would have 2 fields under Config.Display: General and Flags.

Also, since it's a new feature, could you add some tests that verify the order and presence of components is respected. Same for the Delimiter, having a simple test that verifies that this can effectively be changed.
Also, still because this is a new feature, adding 2 lines about it in the README section would be great.

Thank you.
