### ISSUE TITLE
Updates to the git status are slow

### ISSUE THREAD

**Issue by mihai-dinu** [arl/gitmux#20]
## Expected Behavior
Add a new file or branch changes should be reflected sub second in the tmux status bar

## Actual Behavior
Take more than a couple of seconds (most of the times) to update the git status with changes in the tmux status bar

## Steps to Reproduce the Problem

  1. In a repo create a branch and check it out 
  2. Look at the gitmux status on the status bar
  3. Notice that it takes a while (2-3 seconds) for the status to update

## Specifications
  - OS: Pop_OS 19.10
  - gitmux version: `gitmux -V` 0.4.1
  - tmux version: `tmux -V` 2.9a

**Comment by mihai-dinu** [comment]
Nvm, the problem was that I did not have `status-interval` set

```
set -g status-interval 1
```

**Comment by betoharres** [comment]
I had this issue, almost uninstalled it because of this. I experienced this on arch linux fresh install and also on OSX with tmux next 3.3
IMO this should be in the README asap
