### ISSUE TITLE
Space missing from behind the 'staged' symbol in default config

### ISSUE THREAD

**Issue by atleta** [arl/gitmux#24]
Hi,

Minor issue, but a space is missing from behind the ●/staged symbol in the default config in tmux/formatter.go (https://github.com/arl/gitmux/blob/master/format/tmux/formater.go#L55) and it makes that part of the display illegible (at least with the default fixed font on ubuntu). Indeed, I haven't realized what that blob could be until I got myself to look into gitmux config to fix the colors.

I see there's a space after all the other symbols, so this must be accidental or not causing a problem with the font you are using.

## Expected Behavior

![Selection_999(302)](https://user-images.githubusercontent.com/6267837/83876285-e928e500-a738-11ea-9317-d292ee71c9ef.png)

## Actual Behavior

![Selection_999(303)](https://user-images.githubusercontent.com/6267837/83876246-d9110580-a738-11ea-948c-716e12562493.png)

## Specifications
  - OS: Ubuntu 20.04
  - gitmux version: 0.3.2 and 0.5.0
  - tmux version: `tmux -V`

**Comment by arl** [comment]
@atleta thanks for reporting, that is now fixed on master.

**Comment by arl** [comment]
@atleta FYI this is fixed in [latest](https://github.com/arl/gitmux/releases/latest) release
