### ISSUE TITLE
Git info not working with oh-my-tmux setup

### ISSUE THREAD

**Issue by felippemr** [arl/gitmux#28]
## Expected Behavior
Git info appearing on the right-hand side of the tmux bar

## Actual Behavior
Nothing is showing up

## Steps to Reproduce the Problem

  1. Install https://github.com/gpakosz/.tmux
  2. install gitmux
  3. Configure ~/.tmux.conf.local to `tmux_conf_theme_status_right='#{prefix}#{pairing}#{synchronized} #(gitmux "#{pane_current_path}"), #{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{username}#{root} | #{hostname} '`

## Specifications
  - OS: MacOS Catalina(10.15.5)
  - gitmux version: `<<development version>>`
  - tmux version: `tmux 3.1b`

**Comment by felippemr** [comment]
Already tried without `,` after the gitmux conf.

**Comment by arl** [comment]
Thanks for reporting.
Just to be sure there's nothing else did you check that `gitmux` shows when it's put alone in `status-right`

**Comment by felippemr** [comment]
I did not. Let me try.

**Comment by felippemr** [comment]
It still does not work.

**Comment by arl** [comment]
> It still does not work.

To try, did you comment everything in your `tmux.conf` that is about `status-right`, then placed (as per gitmux readme):

    set -g status-right '#(gitmux "#{pane_current_path}")'

After that you need to reload `tmux.conf` 
(either with a shortcut set in `tmux.conf` itself, or by exiting all your tmux session and restating a new one).

Another 'trick' to see if the problem comes from tmux configuration or gitmux itself is to `cd` in a git working tree and simply issue:

`tmux set -g status-right '#(gitmux "#{pane_current_path}")'`

That should work
And reload

**Comment by arl** [comment]
But I strongly suspect a conflict in your tmux configuration file. I do not use oh-my-tmux so I don't know whether it's author explained how to extend the provided status string but anyway since it's just a set of tmux commands there's no reason it shouldn't work

**Comment by felippemr** [comment]
Thanks for your response!

> tmux set -g status-right '#(gitmux "#{pane_current_path}")'

Did not work

**Comment by felippemr** [comment]
Thanks for your response!

> tmux set -g status-right '#(gitmux "#{pane_current_path}")'

👆  did not work

**Comment by felippemr** [comment]
I change `gitmux` to `echo` and the result of current folder appeared. `gitmux` in is my path because I can run it from a bash session but for  some reason tmux can't find it.

**Comment by felippemr** [comment]
`#(/Users/fera/go/bin/gitmux "#{pane_current_path}")` worked!

**Comment by felippemr** [comment]
So it has nothing to do with `oh-my-tmux`.

**Comment by arl** [comment]
> 3. Configure ~/.tmux.conf.local to `tmux_conf_theme_status_right='#{prefix}#{pairing}#{synchronized} #(gitmux "#{pane_current_path}"), #{?battery_status, #{battery_status},}#{?battery_bar, #{battery_bar},}#{?battery_percentage, #{battery_percentage},} , %R , %d %b | #{username}#{root} | #{hostname} '`

So I guess this works now?

**Comment by felippemr** [comment]
Closing since the issue is not related to gitmux.

**Comment by michael-wojcik** [comment]
> `#(/Users/fera/go/bin/gitmux "#{pane_current_path}")` worked!

@felippemr Just wanted to say thanks since this worked for me as well using `oh-my-tmux`

**Comment by arl** [comment]
That'd mean either gitmux is not in the `PATH`,or not in the `PATH` that tmux sees.
Anyway glad to hear this issues is helping others
