### ISSUE TITLE
Enhance README

### ISSUE THREAD

**Issue by arl** [arl/gitmux#3]
Current README doesn't show examples for styling output, nor using showing git status in another part of the status bar, or in a second status bar.

**Comment by c02y** [comment]
I'm using this as my `pane-border-format`:
~~~
set -g pane-border-format "#[reverse,bold]#(echo '#')#{pane_index}: #{s|$HOME|~|:pane_current_path}#[default] (#(gitmux -q -fmt tmux #{pane_current_path})#[default])"
~~~
