### ISSUE TITLE
[BUG] branch name doesn't get fully displayed

### ISSUE THREAD

**Issue by c02y** [arl/gitmux#43]
**Describe the bug**
The branch name is not fully displayed.

I personally put the gitmux inside `pane-border-format`, but I tried to put the config inside `status-right`, it is the same result, 

BTW: The setting is "branch_max_len: 0" in `gitmux --printcfg`, and the branch name is fully displayed when just executing `gitmux`

**To Reproduce**

Steps to reproduce the behavior.
switch to any branch such as master branch

**Expected behavior**
The branch name should be fully displayed if `branch_max_len: 0`

**Screenshots**
![Screenshot_20200906_215055](https://user-images.githubusercontent.com/2135996/92327274-13b57180-f08b-11ea-9a8d-1ab613b3a6be.png)
![Screenshot_20200906_215034](https://user-images.githubusercontent.com/2135996/92327275-14e69e80-f08b-11ea-89f8-c8ef0ca4966f.png)

**Environment:**
 - gitmux version: `0.7.4`
 - tmux version: `tmux 3.1b`
 - OS `5.7.19-2-MANJARO`
 - shell (bash/fish/...) `fish shell`
 - your gitmux config `gitmux.cfg` if you're not using the default one.
default:
```
tmux:
symbols:
branch: '⎇ '
hashprefix: ':'
ahead: ↑·
behind: ↓·
staged: '● '
conflict: '✖ '
modified: '✚ '
untracked: '… '
stashed: '⚑ '
clean: ✔
styles:
state: '#[fg=red,bold]'
branch: '#[fg=white,bold]'
remote: '#[fg=cyan]'
staged: '#[fg=green,bold]'
conflict: '#[fg=red,bold]'
modified: '#[fg=red,bold]'
untracked: '#[fg=magenta,bold]'
stashed: '#[fg=cyan,bold]'
clean: '#[fg=green,bold]'
layout: [branch, .., remote-branch, divergence, ' - ', flags]
options:
branch_max_len: 0
```
 - in case the problem only happens in a specific directory, please paste the
 output of `gitmux -dbg` in that directory.

**Additional context**

**UPDATE**:
Weird thing is: when I'm using a different environment, the branch name got fully displayed:

Not fully displayed:
Manjaro+KDE+Yakuake+gitmux+tmux
Fully displayed:
Manjaro+XFCE+xfce4-terminal+gitmux+tmux

I'll check the KDE environment later.

**Comment by c02y** [comment]
I'm sorry, it seems this is the bug of Konsole/Yakuake, and I don't know how to debug it. I'll close this for now.

**Comment by arl** [comment]
@c02y no worries. Feel free to reopen if you think this has to do with `gitmux`
