### ISSUE TITLE
[FEATURE] Add support for installing via brew

### ISSUE THREAD

**Issue by preslavmihaylov** [arl/gitmux#52]
It would be great if gitmux can be installed via `brew install arl/gitmux` or similar.

**Comment by arl** [comment]
Thanks. I agree that would be nice to have. 👍🏽

**Comment by arl** [comment]
I'm not using mac but would be happy to review a PR adding a brew recipe :)
thanks

**Comment by arl** [comment]
Support for homebrew is live @preslavmihaylov 🎉  
I've updated instructions in the README

**Comment by preslavmihaylov** [comment]
Fantastic, thank you @arl!
