### ISSUE TITLE
[FEATURE] Add style for divergence & default symbols

### ISSUE THREAD

**Issue by preslavmihaylov** [arl/gitmux#53]
I currently can't style the divergence part of gitmux or random symbols specified in the layout:
![image](https://user-images.githubusercontent.com/7642330/134213181-bf3840a5-6064-415a-bf3a-83dd09866f7e.png)

It would be nice for this to be customisable

**Comment by arl** [comment]
Thanks. I agree that would be nice to have. 👍🏽
