### ISSUE TITLE
[FEATURE] trim-from-left branch name

### ISSUE THREAD

**Issue by eladeyal-intel** [arl/gitmux#58]
if branch_max_len > 0

and the branch name is too long

it should truncate by removing the start and leaving the end of the branh name

because may of my branches start with  authorname/  so it's not useful to see just the start.

**Comment by arl** [comment]
We could do that in a backward compatible way by:
 - adding an additonal parameter
 - or by interpreting negative `max_branch_len` as _trim from the end_ and positive ones as _trim from the start_

**Comment by arl** [comment]
@eladeyal-intel the feature is present from version v0.7.6 
latest -> https://github.com/arl/gitmux/releases/latest

**Comment by eladeyal-intel** [comment]
thanks!!! @arl
