### ISSUE TITLE
[FEATURE] ellipisis

### ISSUE THREAD

**Issue by elad-eyal** [arl/gitmux#60]
Use `…` instead of `...` when trimming a branch name (or anything else for that matter)

`…` is only one character wide so using it instead of `...` gives 2 more characters of screen estate.

![image](https://user-images.githubusercontent.com/20379005/150697302-c9fdd9aa-6915-43c4-9b17-310e0df83264.png)

Many fonts that I've tried seems to support this special character, but I guess it should be controllable via options file also.

**Comment by arl** [comment]
Thanks for contributing. I thought about using it while implementing #59 then I wondered if it may not be a slightly wider character plus it's probably not available in all fonts. 
Thanks for opening the issue, having this as an option would indeed be nice.

**Comment by arl** [comment]
@elad-eyal 
`Ellipsis` configuration option has been added in latest gitmux version.
The default config, which you can get with `gitmux -printcfg`, has it. 
Checkout https://github.com/arl/gitmux/releases/tag/v0.9.0
