### ISSUE TITLE
[FEATURE] Count Line Numbers

### ISSUE THREAD

**Issue by joshmedeski** [arl/gitmux#77]
**Is your feature request related to a problem? Please describe.**
As a gitmux user, I want to display the number of lines changed in my repository (instead of number of files changed).

**Describe the solution you'd like**
Add a `count_lines` options to the `gitmux.conf` options.

**Describe alternatives you've considered**
The alternative is to continue using gitmux as-is by displaying number of files changed.

**Additional context**
This isn't a deal breaker, showing file numbers is plenty helpful. But GitHub PRs show line numbers changed and I thin it will help me better prioritize committing early to reduce the chances of over-sized commits.

**Comment by arl** [comment]
Hi @joshmedeski 
Thank you for your interest in gitmux!

That information seems to be easily accessible with `git diff --shortstat`
For example;
```
git diff --shortstat
2 files changed, 10 insertions(+), 6 deletions(-)
```
This exactly matches what github would show in a PR.
How do you suggest that information being presented?
 - Should `16` be shown (sum of additions and deletions)?
 - Should `count_lines` be replaced with some string like `10+/6-`?
 - Something else?

**Comment by joshmedeski** [comment]
I'd like to add the lines changes to something like this, maybe we define 

![gitmux-sample](https://user-images.githubusercontent.com/2036594/212768569-55e30cdf-58c7-45fc-bd70-302aecbabae2.jpg)

Maybe we add this to the config:

```cfg
tmux:
  symbols:
    insertions: ''
    deletions: ''
  styles:
    insertions: ''
    deletions: ''
  layout: [..., insertions, deletions]
```

What do you think? I'm not sure if git supports how many lines have been modified for the whole repo but that would best match the screenshot.

**Comment by arl** [comment]
FYI @joshmedeski this is implemented in latest version
Checkout https://github.com/arl/gitmux/releases/latest

Default configuration has not changed to not break status of gitmux users when they update.
You'll need to add `stats` to the `layout` section
More details in the in the README

**Comment by joshmedeski** [comment]
Thanks, it works like a charm!
