### ISSUE TITLE
[FEATURE] add a "reset" style

### ISSUE THREAD

**Issue by TLINDEN** [arl/gitmux#95]
**Is your feature request related to a problem? Please describe.**

I am using the output of gitmux and the date like so:
```
set -g status-right '#(gitmux -cfg $HOME/.gitmux.conf "#{pane_current_path}") %d.%m.%Y %H:%M:%S'
```

The problem is, that the last item in the gitmux outputs sets some color which will then be used for the date. So sometimes I have a green date, sometimes a magenta one etc.

My current solution is this custom layout in `.gitmux.conf`:
```
layout: [branch, remote-branch, divergence, " - ", flags, "#[fg=default]"]
```

**Describe the solution you'd like**
A style called "reset" or something like that should be added and maybe included in the default layout.

**Comment by arl** [comment]
Hi @TLINDEN 

Thanks for contributing with this issue.
Yeah I agree that it's gitmux responsibility to reset any style modifiers.
I think that there shouldn't even be the need for a new keyword to touch the default config, and that instead it should be baked in.

**Comment by arl** [comment]
@TLINDEN 

This is present in [latest release **v0.10.2**](https://github.com/arl/gitmux/releases/latest)

**Comment by TLINDEN** [comment]
Thanks a lot!
